name: Build and deploy Vue app to Azure Web App - walkiepedia

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Node 22 is not widely stable with tooling yet

      - name: Install dependencies
        run: npm ci

      - name: Build Vue app
        run: npm run build

      - name: Zip dist folder for deployment
        run: zip -r release.zip dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: vue-dist
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: vue-dist

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8007AC4783AF4583B3B6CB60012D22ED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D14B94C55F39487086A435D00B6E304B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1006A8F210AB40F9AC4C82F23927A795 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'walkiepedia'
          slot-name: 'Production'
          package: dist/
